/* categories */
export const FETCH_CATEGORY_DATA = 'FETCH_CATEGORY_DATA'
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'

/* items */
export const FETCH_ITEM_DATA = 'FETCH_ITEM_DATA'
export const UPDATE_MENU_STYLE = 'UPDATE_MENU_STYLE'

/* order */
export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER'
export const REMOVE_ITEM_FROM_ORDER = 'REMOVE_ITEM_FROM_ORDER'

export const ADD_ADDITION_TO_ORDER = 'ADD_ADDITION_TO_ORDER'
export const REMOVE_ADDITION_FROM_ORDER = 'REMOVE_ADDITION_FROM_ORDER'
export const UPADTE_ADDITION = 'UPADTE_ADDITION'

export const UPDATE_ORDER_STYLE = 'UPDATE_ORDER_STYLE'
export const TOGGLE_TOGO_STATUS = 'TOGGLE_TOGO_STATUS'
export const TOGGLE_WHEN_STATUS = 'TOGGLE_WHEN_STATUS'
export const SUBMIT_ORDER = 'SUBMIT_ORDER'

/* pages */
export const CHANGE_MENU_PAGE = 'CHANGE_MENU_PAGE'
export const RESET_MENU_PAGE = 'RESET_MENU_PAGE'

/* tables */
export const FETCH_TABLE_DATA = 'FETCH_TABLE_DATA'
